name: "💡 Task"
description: "Request a new task or improvement."
title: "💡 Task: Title"

body:
  - type: markdown
    attributes:
      value: |
        ## Task Description
        <!-- Describe the task that needs to be completed. -->
        <!-- What problem does this task address? -->
        <!-- Provide detailed expectations and required actions. -->

  - type: textarea
    id: use-case
    attributes:
      label: "Use Case"
      description: "How is this task relevant or beneficial?"
      placeholder: |
        1. Explain specific scenarios or reasons for this task.
        2. Describe the impact or value this task will bring.
    validations:
      required: true
