name: "🔥 Bug Report"
description: "Report a bug, request a feature, or ask a question."
title: "🔥 Bug Report: Title"

body:
  - type: markdown
    attributes:
      value: |
        ## 説明
        <!-- バグ、機能、または質問について説明してください。 -->
        <!-- 期待していた動作は何ですか？ -->
        <!-- 実際に起こったことは何ですか？ -->
        <!-- 機能リクエストの場合は、使用例と提案する解決策を説明してください。 -->
  
  - type: textarea
    id: description
    attributes:
      label: "詳しい説明"
      description: "詳しい説明"
      placeholder: "バグ、機能、または質問について説明してください。期待していた動作は何ですか？実際に起こったことは何ですか？"
    validations:
      required: true

  - type: textarea
    id: possible-solution
    attributes:
      label: "考えられる解決策"
      description: "バグの修正方法や機能の実装について提案がある場合は、ここに記述してください。"
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: "スクリーンショット"
      description: "問題や機能リクエストを説明するためのスクリーンショットがある場合は、ここに追加してください。"
    validations:
      required: false
